"""
Demo Simulator - Simula erros para demonstrar os detetores do AutopsyGuard.

USO:
    uv run python demo_simulator.py --case-dir "C:\Cases\MeuCaso" --error log-severe
    uv run python demo_simulator.py --case-dir "C:\Cases\MeuCaso" --error log-oom
    uv run python demo_simulator.py --case-dir "C:\Cases\MeuCaso" --error jvm-crash
    uv run python demo_simulator.py --case-dir "C:\Cases\MeuCaso" --error solr-error

ERROS DISPONÍVEIS:
    log-severe   → Injeta erro SEVERE no log (LogDetector - WARNING)
    log-oom      → Injeta OutOfMemoryError no log (LogDetector - CRITICAL)
    log-fatal    → Injeta FATAL error no log (LogDetector - CRITICAL)
    jvm-crash    → Cria ficheiro hs_err_pid*.log falso (JvmCrashDetector - CRITICAL)
    solr-error   → Injeta erro no log do Solr (SolrDetector - WARNING)
    solr-oom     → Injeta OOM no log do Solr (SolrDetector - CRITICAL)
"""

import argparse
import os
import platform
import random
import sys
from datetime import datetime
from pathlib import Path


def get_autopsy_user_dir() -> Path:
    """Retorna o diretório de dados do Autopsy no perfil do utilizador."""
    if platform.system() == "Windows":
        return Path(os.environ.get("APPDATA", "")) / "autopsy"
    else:
        return Path.home() / ".autopsy"


def get_case_log_path(case_dir: Path) -> Path:
    """Retorna o caminho do log principal do caso."""
    return case_dir / "Log" / "autopsy.log.0"


def get_solr_log_dir() -> Path:
    """Retorna o diretório de logs do Solr (localização real do Autopsy)."""
    return get_autopsy_user_dir() / "var" / "log" / "solr"


def inject_log_error(case_dir: Path, error_type: str) -> bool:
    """Injeta uma linha de erro no log do Autopsy."""
    log_file = get_case_log_path(case_dir)
    
    if not log_file.parent.exists():
        log_file.parent.mkdir(parents=True, exist_ok=True)
    
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    errors = {
        "log-severe": f"{timestamp} SEVERE [main] Simulated SEVERE error for demo purposes",
        "log-oom": f"{timestamp} SEVERE [main] java.lang.OutOfMemoryError: Java heap space - SIMULATED FOR DEMO",
        "log-fatal": f"{timestamp} FATAL [main] System crash simulated - DEMO ERROR",
        "log-exception": f"{timestamp} WARNING [main] Exception in thread - java.lang.NullPointerException - SIMULATED",
    }
    
    error_line = errors.get(error_type)
    if not error_line:
        print(f"❌ Tipo de erro desconhecido: {error_type}")
        return False
    
    with open(log_file, "a", encoding="utf-8") as f:
        f.write(error_line + "\n")
    
    print(f"✅ Erro injetado em: {log_file}")
    print(f"   Linha: {error_line[:80]}...")
    return True


def create_jvm_crash_file(case_dir: Path) -> bool:
    """Cria um ficheiro de crash JVM falso (hs_err_pid*.log) no diretório HOME."""
    pid = random.randint(10000, 99999)
    # JVM crash files go to user home directory (where JvmCrashDetector looks)
    crash_file = Path.home() / f"hs_err_pid{pid}.log"
    
    crash_content = f"""#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f1234567890, pid={pid}, tid=0x00007f9876543210
#
# JRE version: OpenJDK Runtime Environment (17.0+35) (build 17.0.1+12)
# Java VM: OpenJDK 64-Bit Server VM (17.0.1+12, mixed mode, tiered, compressed oops)
# Problematic frame:
# V  [libjvm.so+0x123456]  JVM_handle_linux_signal+0x123
#
# === SIMULATED CRASH FOR AUTOPSYGUARD DEMO ===
#
# This file was generated by demo_simulator.py
# Created at: {datetime.now().isoformat()}
#
"""
    
    with open(crash_file, "w", encoding="utf-8") as f:
        f.write(crash_content)
    
    print(f"✅ Ficheiro de crash JVM criado: {crash_file}")
    print(f"   (JvmCrashDetector procura em: {Path.home()})")
    return True


def trigger_real_solr_error(error_type: str) -> bool:
    """Provoca um erro REAL no Solr via HTTP request.
    
    Em vez de injetar texto no log (que é sobrescrito pelo buffer do Solr),
    esta função faz pedidos HTTP que causam erros reais que o Solr regista.
    """
    import urllib.request
    import urllib.error
    import json
    
    SOLR_PORT = 23232  # Porta padrão do Solr no Autopsy
    
    print("🔍 A verificar se o Solr está acessível...")
    
    # Check if Solr is running
    try:
        with urllib.request.urlopen(f"http://localhost:{SOLR_PORT}/solr/admin/cores?action=STATUS&wt=json", timeout=5) as resp:
            data = json.loads(resp.read().decode())
            cores = list(data.get("status", {}).keys())
            if not cores:
                print("❌ Solr está a correr mas não tem cores ativos")
                print("   Abra um caso no Autopsy primeiro.")
                return False
            print(f"✅ Solr ativo com {len(cores)} core(s): {cores[0][:30]}...")
    except urllib.error.URLError as e:
        print(f"❌ Não foi possível conectar ao Solr na porta {SOLR_PORT}")
        print(f"   Erro: {e}")
        print("   Certifique-se que o Autopsy está a correr com um caso aberto.")
        return False
    
    # Use the first available core
    core_name = cores[0]
    
    if error_type == "solr-error":
        # Send malformed query that will cause a parse error
        print("📤 A enviar query malformada ao Solr...")
        bad_queries = [
            # Syntax error in query
            f"http://localhost:{SOLR_PORT}/solr/{core_name}/select?q=[[INVALID_SYNTAX&wt=json",
            # Invalid field reference
            f"http://localhost:{SOLR_PORT}/solr/{core_name}/select?q=nonexistent_field_xyz:test&wt=json",
            # Malformed function query
            f"http://localhost:{SOLR_PORT}/solr/{core_name}/select?q={{!func}}invalid_func()&wt=json",
        ]
        
        error_triggered = False
        for url in bad_queries:
            try:
                req = urllib.request.Request(url)
                with urllib.request.urlopen(req, timeout=5) as resp:
                    pass  # If it succeeds, try next
            except urllib.error.HTTPError as e:
                if e.code in (400, 500):
                    print(f"✅ Erro Solr provocado! (HTTP {e.code})")
                    print(f"   O Solr registou este erro no log.")
                    error_triggered = True
                    break
            except Exception:
                pass
        
        if not error_triggered:
            # Try posting invalid XML update
            print("📤 A tentar update com XML inválido...")
            try:
                url = f"http://localhost:{SOLR_PORT}/solr/{core_name}/update?wt=json"
                invalid_xml = b"<add><doc><field>INVALID XML WITHOUT CLOSING TAGS"
                req = urllib.request.Request(url, data=invalid_xml, headers={"Content-Type": "application/xml"})
                urllib.request.urlopen(req, timeout=5)
            except urllib.error.HTTPError as e:
                print(f"✅ Erro Solr provocado! (HTTP {e.code} - XML parse error)")
                error_triggered = True
            except Exception as e:
                print(f"   Falhou: {e}")
        
        if error_triggered:
            print("\n🎯 O AutopsyGuard deve detetar 'ERROR' no solr.log no próximo ciclo!")
            return True
        else:
            print("❌ Não foi possível provocar um erro no Solr")
            return False
            
    elif error_type == "solr-oom":
        # OOM is harder to trigger safely - we'll do a massive facet query
        print("📤 A enviar query pesada para provocar stress no Solr...")
        print("⚠️  NOTA: OOM real é perigoso e pode crashar o Autopsy!")
        print("   A usar query de stress moderada em vez disso...")
        
        # Heavy facet query that logs warnings/errors
        stress_queries = [
            # Request huge number of facets
            f"http://localhost:{SOLR_PORT}/solr/{core_name}/select?q=*:*&rows=0&facet=true&facet.field=text&facet.limit=1000000&wt=json",
            # Deep pagination (causes warnings)  
            f"http://localhost:{SOLR_PORT}/solr/{core_name}/select?q=*:*&start=100000&rows=1000&wt=json",
        ]
        
        for url in stress_queries:
            try:
                req = urllib.request.Request(url)
                with urllib.request.urlopen(req, timeout=30) as resp:
                    data = json.loads(resp.read().decode())
                    # Even if it succeeds, deep pagination logs warnings
                    print("✅ Query de stress executada")
            except urllib.error.HTTPError as e:
                print(f"✅ Query causou erro HTTP {e.code}")
            except Exception as e:
                print(f"   Query falhou: {type(e).__name__}")
        
        print("\n⚠️  OOM real requer memória baixa configurada no Solr.")
        print("   Para testes, use 'solr-error' ou verifique os logs por WARN/ERROR.")
        print("   Logs do Solr: " + str(get_solr_log_dir() / "solr.log"))
        return True
    
    else:
        print(f"❌ Tipo de erro desconhecido: {error_type}")
        return False


def list_available_errors():
    """Lista todos os erros disponíveis para simulação."""
    solr_log_dir = get_solr_log_dir()
    print(f"""
╔═══════════════════════════════════════════════════════════════════════════════╗
║                    DEMO SIMULATOR - Erros Disponíveis                         ║
╠═══════════════════════════════════════════════════════════════════════════════╣
║  ERRO          │ DETETOR         │ SEVERIDADE │ DESCRIÇÃO                     ║
╠═══════════════════════════════════════════════════════════════════════════════╣
║  log-severe    │ LogDetector     │ WARNING    │ Erro SEVERE no log Autopsy    ║
║  log-oom       │ LogDetector     │ CRITICAL   │ OutOfMemoryError no log       ║
║  log-fatal     │ LogDetector     │ CRITICAL   │ Erro FATAL no log             ║
║  jvm-crash     │ JvmCrashDetector│ CRITICAL   │ Cria hs_err_pid*.log falso    ║
║  solr-error    │ SolrDetector    │ WARNING    │ Erro no log do Solr           ║
║  solr-oom      │ SolrDetector    │ CRITICAL   │ OOM no log do Solr            ║
╚═══════════════════════════════════════════════════════════════════════════════╝

LOCALIZAÇÕES DOS FICHEIROS:
  • Logs Autopsy:  <case_dir>/Log/autopsy.log.0
  • Logs Solr:     {solr_log_dir}
  • JVM Crash:     {Path.home()}

EXEMPLO DE USO:
    uv run python demo_simulator.py --case-dir "C:\\Cases\\MeuCaso" --error log-oom

DICA PARA DEMO:
    1. Iniciar AutopsyGuard num terminal
    2. Noutro terminal, correr este script para injetar erros
    3. Ver os alertas a aparecer no Mailtrap
""")


def main():
    parser = argparse.ArgumentParser(
        description="Simula erros para demonstrar os detetores do AutopsyGuard"
    )
    parser.add_argument(
        "--case-dir", "-c",
        type=str,
        help="Diretório do caso Autopsy"
    )
    parser.add_argument(
        "--error", "-e",
        type=str,
        choices=["log-severe", "log-oom", "log-fatal", "jvm-crash", "solr-error", "solr-oom", "list"],
        help="Tipo de erro a simular (use 'list' para ver todos)"
    )
    
    args = parser.parse_args()
    
    if args.error == "list" or (not args.error and not args.case_dir):
        list_available_errors()
        return
    
    # Solr errors - trigger REAL errors via HTTP
    if args.error and args.error.startswith("solr-"):
        success = trigger_real_solr_error(args.error)
        if success:
            print("\n🎯 O AutopsyGuard deve detetar este erro no próximo ciclo de polling")
            print("📧 Verifica o Mailtrap para ver o alerta: https://mailtrap.io/inboxes")
        return
    
    # JVM crash doesn't need case_dir either (goes to home)
    if args.error == "jvm-crash":
        success = create_jvm_crash_file(Path("."))  # case_dir not used
        if success:
            print("\n🎯 O AutopsyGuard deve detetar este erro no próximo ciclo de polling (10s)")
            print("📧 Verifica o Mailtrap para ver o alerta: https://mailtrap.io/inboxes")
        return
    
    if not args.case_dir:
        print("❌ Erro: --case-dir é obrigatório para erros de log")
        print("   Use: --error list para ver opções disponíveis")
        sys.exit(1)
    
    case_dir = Path(args.case_dir)
    
    if not case_dir.exists():
        print(f"⚠️  Diretório não existe, a criar: {case_dir}")
        case_dir.mkdir(parents=True, exist_ok=True)
    
    error_type = args.error
    
    if error_type.startswith("log-"):
        success = inject_log_error(case_dir, error_type)
    else:
        print(f"❌ Erro desconhecido: {error_type}")
        success = False
    
    if success:
        print("\n🎯 O AutopsyGuard deve detetar este erro no próximo ciclo de polling (10s)")
        print("📧 Verifica o Mailtrap para ver o alerta: https://mailtrap.io/inboxes")


if __name__ == "__main__":
    main()
