"""
Demo Simulator - Simula erros para demonstrar os detetores do AutopsyGuard.

USO:
    uv run python demo_simulator.py --case-dir "C:\Cases\MeuCaso" --error log-severe
    uv run python demo_simulator.py --case-dir "C:\Cases\MeuCaso" --error log-oom
    uv run python demo_simulator.py --case-dir "C:\Cases\MeuCaso" --error jvm-crash
    uv run python demo_simulator.py --case-dir "C:\Cases\MeuCaso" --error solr-error

ERROS DISPONÍVEIS:
    log-severe   → Injeta erro SEVERE no log (LogDetector - WARNING)
    log-oom      → Injeta OutOfMemoryError no log (LogDetector - CRITICAL)
    log-fatal    → Injeta FATAL error no log (LogDetector - CRITICAL)
    jvm-crash    → Cria ficheiro hs_err_pid*.log falso (JvmCrashDetector - CRITICAL)
    solr-error   → Injeta erro no log do Solr (SolrDetector - WARNING)
    solr-oom     → Injeta OOM no log do Solr (SolrDetector - CRITICAL)
"""

import argparse
import os
import random
import sys
from datetime import datetime
from pathlib import Path


def get_case_log_path(case_dir: Path) -> Path:
    """Retorna o caminho do log principal do caso."""
    return case_dir / "Log" / "autopsy.log.0"


def get_solr_log_dir(case_dir: Path) -> Path:
    """Retorna o diretório de logs do Solr."""
    return case_dir / "ModuleOutput" / "KeywordSearch"


def inject_log_error(case_dir: Path, error_type: str) -> bool:
    """Injeta uma linha de erro no log do Autopsy."""
    log_file = get_case_log_path(case_dir)
    
    if not log_file.parent.exists():
        log_file.parent.mkdir(parents=True, exist_ok=True)
    
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    errors = {
        "log-severe": f"{timestamp} SEVERE [main] Simulated SEVERE error for demo purposes",
        "log-oom": f"{timestamp} SEVERE [main] java.lang.OutOfMemoryError: Java heap space - SIMULATED FOR DEMO",
        "log-fatal": f"{timestamp} FATAL [main] System crash simulated - DEMO ERROR",
        "log-exception": f"{timestamp} WARNING [main] Exception in thread - java.lang.NullPointerException - SIMULATED",
    }
    
    error_line = errors.get(error_type)
    if not error_line:
        print(f"❌ Tipo de erro desconhecido: {error_type}")
        return False
    
    with open(log_file, "a", encoding="utf-8") as f:
        f.write(error_line + "\n")
    
    print(f"✅ Erro injetado em: {log_file}")
    print(f"   Linha: {error_line[:80]}...")
    return True


def create_jvm_crash_file(case_dir: Path) -> bool:
    """Cria um ficheiro de crash JVM falso (hs_err_pid*.log)."""
    pid = random.randint(10000, 99999)
    crash_file = case_dir / f"hs_err_pid{pid}.log"
    
    crash_content = f"""#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f1234567890, pid={pid}, tid=0x00007f9876543210
#
# JRE version: OpenJDK Runtime Environment (17.0+35) (build 17.0.1+12)
# Java VM: OpenJDK 64-Bit Server VM (17.0.1+12, mixed mode, tiered, compressed oops)
# Problematic frame:
# V  [libjvm.so+0x123456]  JVM_handle_linux_signal+0x123
#
# === SIMULATED CRASH FOR AUTOPSYGUARD DEMO ===
#
# This file was generated by demo_simulator.py
# Created at: {datetime.now().isoformat()}
#
"""
    
    with open(crash_file, "w", encoding="utf-8") as f:
        f.write(crash_content)
    
    print(f"✅ Ficheiro de crash JVM criado: {crash_file}")
    return True


def inject_solr_error(case_dir: Path, error_type: str) -> bool:
    """Injeta erro no log do Solr."""
    solr_log_dir = get_solr_log_dir(case_dir)
    
    if not solr_log_dir.exists():
        solr_log_dir.mkdir(parents=True, exist_ok=True)
    
    # Find or create solr log file
    solr_logs = list(solr_log_dir.glob("solr*.log"))
    if solr_logs:
        log_file = solr_logs[0]
    else:
        log_file = solr_log_dir / "solr.log"
    
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S.%f")[:-3]
    
    errors = {
        "solr-error": f"{timestamp} ERROR (qtp123456-15) [c:autopsy s:shard1 r:core_node1] o.a.s.h.RequestHandlerBase - Simulated Solr error for demo",
        "solr-oom": f"{timestamp} ERROR (qtp123456-15) [c:autopsy] java.lang.OutOfMemoryError: Java heap space - SIMULATED FOR DEMO",
    }
    
    error_line = errors.get(error_type)
    if not error_line:
        print(f"❌ Tipo de erro Solr desconhecido: {error_type}")
        return False
    
    with open(log_file, "a", encoding="utf-8") as f:
        f.write(error_line + "\n")
    
    print(f"✅ Erro Solr injetado em: {log_file}")
    print(f"   Linha: {error_line[:80]}...")
    return True


def list_available_errors():
    """Lista todos os erros disponíveis para simulação."""
    print("""
╔═══════════════════════════════════════════════════════════════════════════════╗
║                    DEMO SIMULATOR - Erros Disponíveis                         ║
╠═══════════════════════════════════════════════════════════════════════════════╣
║  ERRO          │ DETETOR         │ SEVERIDADE │ DESCRIÇÃO                     ║
╠═══════════════════════════════════════════════════════════════════════════════╣
║  log-severe    │ LogDetector     │ WARNING    │ Erro SEVERE no log Autopsy    ║
║  log-oom       │ LogDetector     │ CRITICAL   │ OutOfMemoryError no log       ║
║  log-fatal     │ LogDetector     │ CRITICAL   │ Erro FATAL no log             ║
║  jvm-crash     │ JvmCrashDetector│ CRITICAL   │ Cria hs_err_pid*.log falso    ║
║  solr-error    │ SolrDetector    │ WARNING    │ Erro no log do Solr           ║
║  solr-oom      │ SolrDetector    │ CRITICAL   │ OOM no log do Solr            ║
╚═══════════════════════════════════════════════════════════════════════════════╝

EXEMPLO DE USO:
    uv run python demo_simulator.py --case-dir "C:\\Cases\\MeuCaso" --error log-oom

DICA PARA DEMO:
    1. Iniciar AutopsyGuard num terminal
    2. Noutro terminal, correr este script para injetar erros
    3. Ver os alertas a aparecer no Mailtrap
""")


def main():
    parser = argparse.ArgumentParser(
        description="Simula erros para demonstrar os detetores do AutopsyGuard"
    )
    parser.add_argument(
        "--case-dir", "-c",
        type=str,
        help="Diretório do caso Autopsy"
    )
    parser.add_argument(
        "--error", "-e",
        type=str,
        choices=["log-severe", "log-oom", "log-fatal", "jvm-crash", "solr-error", "solr-oom", "list"],
        help="Tipo de erro a simular (use 'list' para ver todos)"
    )
    
    args = parser.parse_args()
    
    if args.error == "list" or (not args.error and not args.case_dir):
        list_available_errors()
        return
    
    if not args.case_dir:
        print("❌ Erro: --case-dir é obrigatório")
        print("   Use: --error list para ver opções disponíveis")
        sys.exit(1)
    
    case_dir = Path(args.case_dir)
    
    if not case_dir.exists():
        print(f"⚠️  Diretório não existe, a criar: {case_dir}")
        case_dir.mkdir(parents=True, exist_ok=True)
    
    error_type = args.error
    
    if error_type.startswith("log-"):
        success = inject_log_error(case_dir, error_type)
    elif error_type == "jvm-crash":
        success = create_jvm_crash_file(case_dir)
    elif error_type.startswith("solr-"):
        success = inject_solr_error(case_dir, error_type)
    else:
        print(f"❌ Erro desconhecido: {error_type}")
        success = False
    
    if success:
        print("\n🎯 O AutopsyGuard deve detetar este erro no próximo ciclo de polling (10s)")
        print("📧 Verifica o Mailtrap para ver o alerta: https://mailtrap.io/inboxes")


if __name__ == "__main__":
    main()
